### ISSUE TITLE
SSR error

### ISSUE THREAD

**Issue by SOG-web** [ng-primitives/ng-primitives#68]
### Affected Primitive

input

### Version

0.10.0

### Bug Description

`ERROR ReferenceError: document is not defined
    at StyleInjector.add (/Users/rou/Documents/Github/synckron/node_modules/ng-primitives/fesm2022/ng-primitives-internal.mjs:82:30)
    at new NgpAutofill (/Users/rou/Documents/Github/synckron/node_modules/ng-primitives/fesm2022/ng-primitives-autofill.mjs:50:28)
    at NodeInjectorFactory.NgpAutofill_Factory [as factory] (ng:///NgpAutofill/ɵfac.js:5:10)
    at getNodeInjectable (/Users/rou/Documents/Github/synckron/node_modules/@angular/core/fesm2022/core.mjs:6072:44)
    at instantiateAllDirectives (/Users/rou/Documents/Github/synckron/node_modules/@angular/core/fesm2022/core.mjs:12819:27)
    at createDirectivesInstances (/Users/rou/Documents/Github/synckron/node_modules/@angular/core/fesm2022/core.mjs:12215:5)
    at ɵɵelementStart (/Users/rou/Documents/Github/synckron/node_modules/@angular/core/fesm2022/core.mjs:24350:9)
    at Module.ɵɵelement (/Users/rou/Documents/Github/synckron/node_modules/@angular/core/fesm2022/core.mjs:24408:5)
    at InputComponent_Template (/Users/rou/Documents/Github/synckron/shared/src/lib/ui/input.component.ts:17:35)
    at executeTemplate (/Users/rou/Documents/Github/synckron/node_modules/@angular/core/fesm2022/core.mjs:12175:9)
`

### Steps to Reproduce

any angular ssr enabled or analogjs

**Comment by ashley-hunter** [comment]
Thank you very much for the bug report, I have resolved the issue and it should be available in the 0.11.0 release.
